/**
 * Standardized error codes for the CariCash Nova API.
 * Used in error responses and for programmatic error handling.
 */
export const ErrorCode = {
  // Ledger / posting errors
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  CROSS_CURRENCY_NOT_ALLOWED: 'CROSS_CURRENCY_NOT_ALLOWED',
  UNBALANCED_JOURNAL: 'UNBALANCED_JOURNAL',
  DUPLICATE_IDEMPOTENCY_CONFLICT: 'DUPLICATE_IDEMPOTENCY_CONFLICT',
  IDEMPOTENCY_IN_PROGRESS: 'IDEMPOTENCY_IN_PROGRESS',
  JOURNAL_NOT_FOUND: 'JOURNAL_NOT_FOUND',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',

  // Governance / approval errors
  MAKER_CHECKER_REQUIRED: 'MAKER_CHECKER_REQUIRED',
  MAKER_CHECKER_VIOLATION: 'MAKER_CHECKER_VIOLATION',
  APPROVAL_NOT_FOUND: 'APPROVAL_NOT_FOUND',
  APPROVAL_ALREADY_DECIDED: 'APPROVAL_ALREADY_DECIDED',

  // Auth errors
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Actor errors
  ACTOR_NOT_FOUND: 'ACTOR_NOT_FOUND',
  ACTOR_SUSPENDED: 'ACTOR_SUSPENDED',
  DUPLICATE_IDENTIFIER: 'DUPLICATE_IDENTIFIER',

  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

  // Reconciliation / ops errors
  RECONCILIATION_MISMATCH: 'RECONCILIATION_MISMATCH',
  INTEGRITY_VIOLATION: 'INTEGRITY_VIOLATION',
  REPAIR_FAILED: 'REPAIR_FAILED',

  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
} as const;
export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];
