export const EventName = {
  // Auth events
  AUTH_LOGIN_ATTEMPTED: 'AUTH_LOGIN_ATTEMPTED',
  AUTH_LOGIN_SUCCEEDED: 'AUTH_LOGIN_SUCCEEDED',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_PIN_CHANGED: 'AUTH_PIN_CHANGED',
  AUTH_SESSION_CREATED: 'AUTH_SESSION_CREATED',
  // Actor lifecycle
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMER_KYC_INITIATED: 'CUSTOMER_KYC_INITIATED',
  CUSTOMER_KYC_APPROVED: 'CUSTOMER_KYC_APPROVED',
  CUSTOMER_KYC_REJECTED: 'CUSTOMER_KYC_REJECTED',
  AGENT_CREATED: 'AGENT_CREATED',
  MERCHANT_CREATED: 'MERCHANT_CREATED',
  STAFF_CREATED: 'STAFF_CREATED',
  // Transaction events
  TXN_INITIATED: 'TXN_INITIATED',
  TXN_VALIDATED: 'TXN_VALIDATED',
  TXN_AUTHORIZED: 'TXN_AUTHORIZED',
  TXN_POSTED: 'TXN_POSTED',
  TXN_COMPLETED: 'TXN_COMPLETED',
  TXN_FAILED: 'TXN_FAILED',
  // Reversal
  REVERSAL_REQUESTED: 'REVERSAL_REQUESTED',
  REVERSAL_APPROVED: 'REVERSAL_APPROVED',
  REVERSAL_REJECTED: 'REVERSAL_REJECTED',
  REVERSAL_POSTED: 'REVERSAL_POSTED',
  // Approval / Maker-checker
  APPROVAL_CREATED: 'APPROVAL_CREATED',
  APPROVAL_APPROVED: 'APPROVAL_APPROVED',
  APPROVAL_REJECTED: 'APPROVAL_REJECTED',
  // Configuration
  FEE_MATRIX_CREATED: 'FEE_MATRIX_CREATED',
  FEE_MATRIX_APPROVED: 'FEE_MATRIX_APPROVED',
  COMMISSION_MATRIX_CREATED: 'COMMISSION_MATRIX_CREATED',
  COMMISSION_MATRIX_APPROVED: 'COMMISSION_MATRIX_APPROVED',
  // Overdraft
  OVERDRAFT_FACILITY_CREATED: 'OVERDRAFT_FACILITY_CREATED',
  OVERDRAFT_FACILITY_APPROVED: 'OVERDRAFT_FACILITY_APPROVED',
  // Audit
  AUDIT_PRIVILEGED_ACTION: 'AUDIT_PRIVILEGED_ACTION',
  MANUAL_ADJUSTMENT_REQUESTED: 'MANUAL_ADJUSTMENT_REQUESTED',
  MANUAL_ADJUSTMENT_APPROVED: 'MANUAL_ADJUSTMENT_APPROVED',
  MANUAL_ADJUSTMENT_POSTED: 'MANUAL_ADJUSTMENT_POSTED',
  // Reconciliation & Ops (Phase 2)
  RECONCILIATION_STARTED: 'RECONCILIATION_STARTED',
  RECONCILIATION_COMPLETED: 'RECONCILIATION_COMPLETED',
  RECONCILIATION_MISMATCH_FOUND: 'RECONCILIATION_MISMATCH_FOUND',
  ALERT_RAISED: 'ALERT_RAISED',
  SUSPENSE_AGING_DETECTED: 'SUSPENSE_AGING_DETECTED',
  INTEGRITY_CHECK_PASSED: 'INTEGRITY_CHECK_PASSED',
  INTEGRITY_CHECK_FAILED: 'INTEGRITY_CHECK_FAILED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  REPAIR_EXECUTED: 'REPAIR_EXECUTED',
} as const;
export type EventName = typeof EventName[keyof typeof EventName];
